name: Start Minecraft Server

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  start-server:
    runs-on: ubuntu-latest  # Runs on GitHub's cloud

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok -y
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start Minecraft Server
        run: |
          java -Xmx6288M -Xms6288M -jar server.jar nogui &

      - name: Start Ngrok
        run: |
          ./ngrok tcp 25565 > ngrok.log &
          sleep 10
          cat ngrok.log
